export enum GameMessage {
  ClickSpin = 'ClickSpin',
  GoodLuck = 'GoodLuck',
  LineWin = 'LineWin',
  AllWaysWin = 'AllWaysWin',
  YouWin = 'YouWin',
  BigWin = 'BigWin',
  ScatterWin = 'ScatterWin',
  ClickStartContinue = 'ClickStartContinue',
  ClickStart = 'ClickStart',
  ClickTake = 'ClickTake',
  AddMoneyFail = 'AddMoneyFail',
  PurchaseHint = 'PurchaseHint',
  DonateHint = 'DonateHint',
  FeatureWin = 'FeatureWin',
  FeatureWin_CustomGame = 'FeatureWin_CustomGame',
  WaitSelectSecond = 'WaitSelectSecond',
  WaitStopSecond = 'WaitStopSecond',
  JackpotWin = 'JackpotWin',
  ChooseOne = 'ChooseOne',
}
