export enum BQLoggerFunction {
  SendEventLog = 'BQLOG_SendEventLog',
  SendErrorLog = 'BQLOG_SendErrorLog',
  SendLoadGameSettingFailed = 'BQLOG_SendLoadGameSettingFailed',
  SendParseGameSettingFailed = 'BQLOG_SendParseGameSettingFailed',
  SendGetServerDataFailed = 'BQLOG_SendGetServerDataFailed',
  SendLoadResFailed = 'BQLOG_SendLoadResFailed',
  SendLoginFailed = 'BQLOG_SendLoginFailed',
  SendLoadSceneComplete = 'BQLOG_SendLoadSceneComplete',
  SendLoadGameComplete = 'BQLOG_SendLoadGameComplete',
  SendClickPlay = 'BQLOG_SendClickPlay',
  SendSeeGameScene = 'BQLOG_SendSeeGameScene',
  SendPlaySuccess = 'BQLOG_SendPlaySuccess',
  SendStartGameError = 'BQLOG_SendStartGameError',
  SendSpinError = 'BQLOG_SendSpinError',
  SendNextFeverError = 'BQLOG_SendNextFeverError',
  SendInGameJPError = 'BQLOG_SendInGameJPError',
  SendDataError = 'BQLOG_SendDataError',
}
